### ISSUE TITLE
DNA improvements

### ISSUE THREAD

**Issue by ncave** [kaby76/Campy#1]
Hello fellow DNA enthusiast!

This is not really an issue, more of a question.

As a maintainer of another [DNA clone](https://github.com/ncave/dna-redux), it would be very interesting to understand better the extent of your changes on top of the original DNA (a Blazor fork as baseline, I assume), for example what did you fix for 64-bit support, or anything else from the top of your head that you wish to share.

Just skimming through the code, I see these changes:
- added function_space_specifier to functions
- replaced allocation functions
- replaced string functions
- replaced the JIT and the JIT runner with Mono.Cecil (but why).

I'm sure this only touches the surface, perhaps I'm missing some of the changes.

Looks like an awesome project, the GPU target looks very interesting.

Thank you, I appreciate your help and time.

**Comment by kaby76** [comment]
I agree, let's try to coordinate on getting DNA sources aligned. There are some kludges in my branch now, so those will need to be fixed, and will take some time, probably a few months from now. The NVIDIA GPU has some really restrictive alignment and size issues, so that will need to be somehow abstracted out. Right now it's being baked in, just like before.

The JIT/interpreter was removed from my branch of DNA because the compiler is way over in another library, Campy.Compiler. From my perspective, the DNA is just a library, no compiler, which may be wrong. It uses Mono.Cecil because it has a way to edit the IL. I need that because (1) it has a nice layer abstracting instructions that I can put a wrapper around. Also as the IL of a program is analyzed, some of the code has to be rewritten to use the DNA framework instead of what the code was originally compiled against. After JIT, the user data structures are copied to GPU/CPU share pinned memory (currently), the compiled code linked against the DNA native code, and then launched. The compiler actually uses both Mono.Cecil and the DNA meta system, and that's pretty kludgy. DNA should be able do it all.

**Comment by ncave** [comment]
@kaby76 I see, it's a bit different use case then, as there is no need for IL alterations for non-GPU targets. Still, it looks like it would not be hard to align the DNA source by adding your changes and disable the parts you don't need with conditionals. Let me know when you are a good place and I'll be happy to help with that, in either of the existing repos or in a new one if you prefer.
